CREATE TABLE `author` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(40) NOT NULL,
  `SEX` char(1) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `book` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ISBN` char(10) NOT NULL,
  `TITLE` varchar(100) DEFAULT NULL,
  `AUTHOR` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ISBN_UNIQUE` (`ISBN`),
  KEY ` BOOKAUTHOR_idx` (`AUTHOR`),
  CONSTRAINT ` BOOKAUTHOR` FOREIGN KEY (`AUTHOR`) REFERENCES `author` (`ID`),
  CONSTRAINT `FK9wwmvcc520honrafnyi2gkdj4` FOREIGN KEY (`AUTHOR`) REFERENCES `author` (`ID`)
);
